a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
print(type(a))
print(type(b))
print("Addition is",a+b)
print("Subtraction is",a-b)
print("Multiplication is",a*b)
print("Division is",a/b)
print("Remainder is",a%b)